version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ranking-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ranking_db
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
